[tool.black]
line-length = 88
target-version = ["py312"]
include = '\.pyi?$'
exclude = '''/
(
  \.git
  | \.venv
  | build
  | dist
)
/'''

[tool.flake8]
max-line-length = 88
extend-ignore = E203, W503
exclude = .git,__pycache__,dist,build,desktop/node_modules,desktop/renderer/dist,desktop/dist-electron

[tool.mypy]
python_version = 3.12
ignore_missing_imports = true
warn_return_any = false
warn_unused_configs = false
